export interface ProgrammeOption {
  code: string;
  name: string;
  category?: string;
  active: boolean;
}

const PROGRAMME_CODES: string[] = [
  'ACE','ACFS','ACISE','ACPDM','ACPSD','ACSEPD','ACSM','ADACM','ADAOM','ADCM','ADIT','ADTS','AIPR','APDF','APSMBIO','APSMG','APSMW','APSS','APVPFV','ASSO','ATPD',
  'BA','BAADM','BAAHD','BAAPS','BAAS','BAASK','BAASLS','BAASMSME','BAASTM','BAAUD','BAAVFX','BABED','BACT','BAECH','BAEGH','BAFC','BAFD','BAFEC','BAFEDU','BAFEG','BAFFSM','BAFHD','BAFHI','BAFHSC','BAFJDM','BAFMP','BAFPA','BAFPC','BAFPS','BAFPY','BAFSK','BAFSM','BAFSO','BAFUD','BAFVTM',
  'BAG','BAGS','BAHDH','BAHIH','BAIHA','BAJDM','BAM','BAMSAPS','BAMSME','BAPAH','BAPCH','BAPFHMH','BAPSH','BARCH','BASKH','BASOH','BATS','BATSOL','BAUDH','BAVMSME','BAVTM',
  'BBA','BBARIL','BBARL','BBARS','BBARSDL','BBASM',
  'BCA','BCAOL','BCA_NEW','BCA_NEWOL',
  'BCOM','BCOMAF','BCOMAPS','BCOMAS','BCOMBED','BCOMCAA','BCOMF','BCOMFCA','BCOMFOL','BCOMG','BCOMOL',
  'BCSSI','BED','BEDSE','BEDSEHI','BEDSEMR','BEDSEVI','BFSW','BFTTM','BFTTMOL','BHM','BIHM','BIT','BLIS','BLISOL','BMIT','BMLT','BMRHIT','BNS','BPAFHM','BPCCHN','BPP','BPPDS','BRTT',
  'BSC','BSCAEY','BSCANH','BSCAPS','BSCAS','BSCBCH','BSCBED','BSCFAN','BSCFBC','BSCFFAD','BSCFFSQM','BSCFLAD','BSCFMRM','BSCFMT','BSCFWP','BSCFWT','BSCG','BSCHIHA','BSCHOT','BSCLGAD','BSCM','BSCN','BSCRFM',
  'BSW','BSWG','BSWGOL',
  'BTAE','BTCLEVI','BTCM','BTCSVI','BTECVI','BTELVI','BTMAPS','BTME','BTMEVI','BTS','BTSOL','BTWRE',
  'CAFE','CAHC','CAHT','CAIS','CAL','CALOL','CAP','CAPMER','CARH','CAY','CBED','CBKG','CBS','CCDP','CCEANM','CCH','CCITSK','CCITSKOL','CCJSW','CCLBL','CCLC','CCMH','CCOMO','CCP','CCPD','CCR','CCSS','CDCW','CDM','CDNK','CDNMA','CDO','CDTP','CELL','CEMBA','CEMPA','CES','CESECP','CESEHI','CESEIHI','CESEIID','CESEIVI','CESEMR','CESEVI','CETE','CETM','CEVMT','CFAID','CFBO','CFDE','CFE','CFL','CFLOL','CFN','CFNOL','CFO','CFS','CFSTY','CGAS','CGCA','CGDA','CGHC','CGL','CGMSM','CGSCI','CGSL','CHAA','CHBCP','CHBHC','CHCWM','CHET','CHHA','CHO','CHR','CIAP','CIAT','CIB','CIC','CICTAL','CIE','CIF','CIG','CIHL','CIS','CIT','CITOL','CITSM','CJD','CJL','CKLC','CLD','CLGM','CLIS','CLISOL','CLL','CLP','CLTA','CMAD','CMCHC','CMCHN','CMSR','CNCC','CNIC','CNIN','CNM','COF','CPA','CPABN','CPAHM','CPAKM','CPAKP','CPAKT','CPAM','CPAMP','CPAOS','CPAT','CPATHA','CPDT','CPE','CPEL','CPF','CPFM','CPHA','CPHN','CPISAS','CPLT','CPPDPT','CPPL','CPS','CPSCM','CPSCMOL','CPSK','CPSL','CPT','CPVE','CPY','CRCS','CRD','CRDOL','CRF','CRFF','CRH','CRHT','CRM','CRS','CRUL','CRULOL','CSCDM','CSEPD','CSI','CSLC','CSLCOL','CSLF','CSM','CSSA','CSUC','CSUS','CSWATT','CSWCJS','CSWM','CTAO','CTE','CTGS','CTPM','CTRBS','CTRBSOL','CTS','CTSOL','CTVM','CUL','CULOL','CVA','CVAA','CVAP','CVAS','CVG','CWDL','CWED','CWHM','CYP',
  'DACM','DAFE','DAPMER','DAPMERA','DAQ','DBPOFA','DCCN','DCE','DCEOL','DCH','DCIM','DCLC','DCLE','DCLEG','DCLEVI','DCSVI','DCUL','DCYP','DDT','DECE','DECVI','DELED','DELVI','DEME','DESD','DEVMT','DFDR','DFPT','DFS','DFSTYM','DHORT','DHOTRM','DIM','DIPP','DIR','DIRIL','DME','DMEVI','DMLT','DMOP','DMT','DNA','DNHE','DNHEOL','DNS','DPE','DPLAD','DPVCPO','DPVE','DRIT','DSCDM','DSM','DTG','DTH','DTS','DTSOL','DUL','DULOL','DVAPFV','DWED','DWM',
  'EMBAHM','EMBAIHM','EMBAIT','EXMBA','FCED','GST','IPHDPA','LPHECO','LPNSSD',
  'MAAE','MAAN','MAANY','MAAPM','MAARB','MAAUD','MABGS','MACSR','MADE','MADEOL','MADJ','MADP','MADVS','MAEC','MAEDS','MAEDU','MAEG','MAEMPM','MAENOH','MAEOH','MAER','MAEVS','MAFCS','MAFL','MAFRM','MAGD','MAH','MAHD','MAHI','MAHN','MAHUE','MAHV','MAJDM','MAJDMOL','MAJEM','MAJMC','MAJMCOL','MAJMCT','MAJY','MAMIDI','MAPC','MAPD','MAPFHS','MAPS','MAPY','MARD','MARDOL','MARUS','MASA','MASAS','MASL','MASO','MASS','MASSOL','MATS','MATSOL','MAUD','MAUS','MAVS','MAWGS','MAWGSCL','MAWGSR',
  'MBA','MBAABM','MBAAVBM','MBABFEV','MBABM','MBACG','MBACN','MBACT','MBAEV','MBAFM','MBAFT','MBAHCHM','MBAHM','MBAIHM','MBAITM','MBALS','MBAMAFCI','MBAMM','MBANIM','MBAOL','MBAOM','MBARS','MBASCMFL','MBATEXM','MBF',
  'MCA','MCAOL','MCA_NEW',
  'MCOM','MCOMBPCG','MCOMFT','MCOMIDT','MCOMMAFS','MCOMOL',
  'MEC','MED','MEDSEHI','MEDSELD','MEDSEMR','MEDSEVI','MEG','MEGOL','MFAP','MGPS','MGPSOL','MHA','MHD','MHDOL','MIPL','MLD','MLIS','MP','MPA','MPAHVM','MPATHA','MPB','MPHIL','MPHILCHEM','MPHILCOM','MPHILDE','MPHILEC','MPHILGEOG','MPHILJMC','MPHILPS','MPHILRSO','MPHILSO','MPHILSOC','MPHILSW','MPHILTH','MPHILTT','MPP','MPS','MPSOL','MSBOBI','MSBOCC','MSBOMM','MSBOT','MSCAEC','MSCAIML','MSCANCHEM','MSCAS','MSCAST','MSCBCH','MSCBIBO','MSCCAD','MSCCC','MSCCFT','MSCCHEM','MSCCRD','MSCDFSM','MSCDSA','MSCENV','MSCFDP','MSCFMRM','MSCFSQM','MSCFWT','MSCGG','MSCGI','MSCHSC','MSCIDS','MSCIS','MSCLGAD','MSCLSC','MSCMACS','MSCPH','MSCRFM','MSCRWEE','MSCVMCD','MSCZOO','MSK','MSKOL','MSNN','MSO','MSST','MSW','MSWC','MSWNE','MSWOL','MSWP','MTECHAE','MTECHCS','MTECHESD','MTECHISS','MTECHNB','MTECHNE','MTECHSD','MTECHSR','MTECHST','MTECHTC','MTECHTS','MTECHVD','MTM','MTTM','MTTM_NEW',
  'NCDCP','NIPDF','NIPFPP','NIPOA','NIPWM','PCSEPD','PDCDM','PGCACP','PGCAE','PGCAP','PGCAPOL','PGCAR','PGCBGSA','PGCBHT','PGCCC','PGCCL','PGCCL_OL','PGCCP','PGCE','PGCEDS','PGCENC','PGCEPD','PGCGI','PGCGPS','PGCGPSOL','PGCHI','PGCIATIVI','PGCIERA','PGCINDS','PGCIPWS','PGCIV','PGCMDM','PGCMHT','PGCMI','PGCML','PGCMRR','PGCOI','PGCP','PGCPDN','PGCPDT','PGCPM','PGCPP','PGCPPK','PGCQM','PGCRW','PGCSO','PGCSRVS','PGCTW','PGCULSA','PGDAB','PGDAC','PGDACP','PGDAE','PGDAIC','PGDAML','PGDAPP','PGDAST','PGDAW','PGDBD','PGDBE','PGDBLT','PGDBP',
  'PGDCA','PGDCA_NEW','PGDCC','PGDCCC','PGDCFT','PGDCJ','PGDCOUN','PGDCSR','PGDDC','PGDDCOL','PGDDE','PGDDEOL','PGDDHM','PGDDM','PGDDRRM','PGDDVS','PGDECFE','PGDEDS','PGDEL','PGDEMA','PGDEME','PGDEML','PGDENLW','PGDENLWOL','PGDENOH','PGDENOHOL','PGDEOH','PGDEOHOL','PGDESD','PGDET','PGDEVS','PGDEVSOL','PGDFCS','PGDFIMKT','PGDFM','PGDFMP','PGDFSQM','PGDFSTYD','PGDFSTYDM','PGDFT','PGDGBL','PGDGBLFF','PGDGBLP','PGDGBLPT','PGDGI','PGDGM','PGDGPS','PGDGPSOL','PGDHAM','PGDHE','PGDHEM','PGDHHM','PGDHIVM','PGDHO','PGDHRM','PGDHUE','PGDIBO','PGDICG','PGDIDM','PGDIDMOL','PGDIE','PGDIFM','PGDIHRM','PGDIMM','PGDINDS','PGDINDSOL','PGDIOM','PGDIPR','PGDIS','PGDISM','PGDLAN','PGDLPO','PGDMCH','PGDMD','PGDMH','PGDMIDI','PGDMISHE','PGDMM','PGDMRR','PGDNLEG','PGDNOV','PGDOM','PGDPD','PGDPDN','PGDPFHS','PGDPM','PGDPPED','PGDPSM','PGDRBI','PGDRD','PGDRDOL','PGDREPY','PGDREPYDL','PGDRP','PGDRPC','PGDSHST','PGDSIC','PGDSLM','PGDSO','PGDSS','PGDSSOL','PGDSW','PGDSWT','PGDT','PGDTAC','PGDTCD','PGDTRBS','PGDTRM','PGDUG','PGDUPDL','PGDVS','PGDVSSA','PGDWAM','PGDWGS','PGDWGSR','PGDWI','PGDWM','PGJMC','PGJMCOL','PGJMCT','PGPCSEHI','PGPCSEMR','PGPCSEVI','PGPDSEHI','PGPDSEMR','PGPDSEVI','PGSKT',
  'PHD','PHDAE','PHDAGE','PHDAL','PHDAN','PHDBC','PHDCD','PHDCDEV','PHDCEE','PHDCEM','PHDCENG','PHDCHE','PHDCHEM','PHDCISC','PHDCMCE','PHDCO','PHDCOM','PHDCS','PHDDE','PHDDR','PHDDS','PHDDV','PHDEC','PHDEDS','PHDEDU','PHDENG','PHDES','PHDEV','PHDFA','PHDFL','PHDFN','PHDGDS','PHDGEOG','PHDGG','PHDGTS','PHDGY','PHDHC','PHDHIN','PHDHIS','PHDITS','PHDJMC','PHDLE','PHDLIS','PHDLS','PHDMCE','PHDMD','PHDMGMT','PHDMT','PHDMTED','PHDMU','PHDNS','PHDNUR','PHDPA','PHDPC','PHDPH','PHDPS','PHDPVA','PHDPVA(D)','PHDPVA(F)','PHDPVA(T)','PHDRD','PHDRSO','PHDSK','PHDSOC','PHDSTAT','PHDSW','PHDTH','PHDTS','PHDTT','PHDUL','PHDVE','PHDVED','PHDWS',
  'QNM101','QPNM','SAVINI','SSB','SSBOL'
];

// Helper labels for famous programmes
const PROGRAMME_LABELS: Record<string, string> = {
  BCA: 'Bachelor of Computer Applications',
  MCA: 'Master of Computer Applications',
  BAG: 'Bachelor of Arts (General)',
  BCOMG: 'Bachelor of Commerce (General)',
  BSCG: 'Bachelor of Science (General)',
  BSW: 'Bachelor of Social Work',
  BLIS: 'Bachelor of Library & Information Science',
  BTS: 'Bachelor of Tourism Studies',
  BBA: 'Bachelor of Business Administration',
  BED: 'Bachelor of Education',
  MAH: 'Master of Arts (History)',
  MEG: 'Master of Arts (English)',
  MHD: 'Master of Arts (Hindi)',
  MPS: 'Master of Arts (Political Science)',
  MSO: 'Master of Arts (Sociology)',
  MCOM: 'Master of Commerce',
  MBA: 'Master of Business Administration',
  MSW: 'Master of Social Work',
  MSC: 'Master of Science',
  PGDCA: 'Post Graduate Diploma in Computer Applications',
  PGDRD: 'Post Graduate Diploma in Rural Development',
  CIT: 'Certificate in Information Technology',
  CFN: 'Certificate in Food and Nutrition',
  PHD: 'Doctor of Philosophy'
};

export const IGNOU_PROGRAMMES: ProgrammeOption[] = PROGRAMME_CODES.map((code) => ({
  code,
  name: PROGRAMME_LABELS[code] || `${code} Programme`,
  active: true
}));
